### ISSUE TITLE
Metrics are not being served

### ISSUE THREAD

**Issue by mcgrizzz** [markusressel/fan2go#159] opened 2022-09-28 23:56 UTC
**Describe the bug**
With the statistics enabled in the config, the /metrics endpoint serves no response. 

**To Reproduce**

1. Enable statistics in the config according to the readme
2. Start fan2go
3. Observe fan2go prints "Starting statistics server..."
4. Try to reach configured end point using curl, web browser, or through Prometheus (http://localhost:9000/metrics)
5. Receive empty response from end point

**Expected behavior**
The /metrics endpoint should serve a non-empty response that can be fed into Prometheus

**Screenshots**

**Desktop (please complete the following information):**

- Distro: Arch Linux
- `uname -a`: `Linux eregion 5.19.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 24 Sep 2022 18:24:15 +0000 x86_64 GNU/Linux`
- `sensors -v`: `sensors version 3.6.0+git with libsensors version 3.6.0+git`
- `fan2go version`: `dev`

**Additional context**

**Comment by markusressel** [comment] 2022-09-30 00:19
You don't need the `/metrics` suffix because the prometheus endpoint will use its own port and webserver.
http://localhost:9000 will work.

**Comment by markusressel** [comment] 2022-09-30 00:36
Thx for reporting, however I cannot reproduce the issue.

Running the latest dev version I can see metrics at:
http://localhost:9000/metrics
as well as
http://localhost:9000

This is the relevant configuration:

```
statistics:
  enabled: true
  port: 9000
```

**Comment by mcgrizzz** [comment] 2022-09-30 03:24
Thank you for your response. 

I'm not sure if this helps narrow the focus on the issue, but if I leave my browser loading the metrics url, then start fan2go while it's still loading, the page will load instantly. 

It seems it will only load as fan2go is starting. Then, any subsequent requests hang and receive an empty response. 

I've attached my config file and a script it references incase there is something relevant there:

`fan2go.yaml`
```YAML
# A list of fans to control
fans:
  # A user defined ID.
  # Used for logging only
  - id: CPU_FRONT
    # The type of fan configuration, one of: hwmon | file
    hwmon:
      # The platform of the controller which is
      # connected to this fan (see sensor.platform below)
      platform: nct6683-isa-0
      # The index of this fan as displayed by `fan2go detect`
      index: 1
    # Indicates whether this fan should never stop rotating, regardless of
    # how low the curve value is
    neverStop: true
    # The curve ID that should be used to determine the
    # speed of this fan
    curve: gpu_curve
    
  - id: FRONT_BOTTOM
    # The type of fan configuration, one of: hwmon | file
    hwmon:
      # The platform of the controller which is
      # connected to this fan (see sensor.platform below)
      platform: nct6683-isa-0
      # The index of this fan as displayed by `fan2go detect`
      index: 2
    # Indicates whether this fan should never stop rotating, regardless of
    # how low the curve value is
    neverStop: true
    # The curve ID that should be used to determine the
    # speed of this fan
    curve: gpu_curve
  - id: CPU_MIDDLE
    # The type of fan configuration, one of: hwmon | file
    hwmon:
      # The platform of the controller which is
      # connected to this fan (see sensor.platform below)
      platform: nct6683-isa-0
      # The index of this fan as displayed by `fan2go detect`
      index: 3
    # Indicates whether this fan should never stop rotating, regardless of
    # how low the curve value is
    neverStop: true
    # The curve ID that should be used to determine the
    # speed of this fan
    curve: gpu_curve
  - id: BOTTOM_MIDDLE
    # The type of fan configuration, one of: hwmon | file
    hwmon:
      # The platform of the controller which is
      # connected to this fan (see sensor.platform below)
      platform: nct6683-isa-0
      # The index of this fan as displayed by `fan2go detect`
      index: 4
    # Indicates whether this fan should never stop rotating, regardless of
    # how low the curve value is
    neverStop: true
    # The curve ID that should be used to determine the
    # speed of this fan
    curve: gpu_curve
  - id: BOTTOM_LEFT
    # The type of fan configuration, one of: hwmon | file
    hwmon:
      # The platform of the controller which is
      # connected to this fan (see sensor.platform below)
      platform: nct6683-isa-0
      # The index of this fan as displayed by `fan2go detect`
      index: 5
    # Indicates whether this fan should never stop rotating, regardless of
    # how low the curve value is
    neverStop: true
    # The curve ID that should be used to determine the
    # speed of this fan
    curve: gpu_curve
  - id: FRONT_TOP
    # The type of fan configuration, one of: hwmon | file
    hwmon:
      # The platform of the controller which is
      # connected to this fan (see sensor.platform below)
      platform: nct6683-isa-0
      # The index of this fan as displayed by `fan2go detect`
      index: 6
    # Indicates whether this fan should never stop rotating, regardless of
    # how low the curve value is
    neverStop: true
    # The curve ID that should be used to determine the
    # speed of this fan
    curve: gpu_curve
  - id: BOTTOM_RIGHT
    # The type of fan configuration, one of: hwmon | file
    hwmon:
      # The platform of the controller which is
      # connected to this fan (see sensor.platform below)
      platform: nct6683-isa-0
      # The index of this fan as displayed by `fan2go detect`
      index: 7
    # Indicates whether this fan should never stop rotating, regardless of
    # how low the curve value is
    neverStop: true
    # The curve ID that should be used to determine the
    # speed of this fan
    curve: gpu_curve

sensors:
  - id: cmd_max_gpu
    cmd:
      # Path to the executable to run to retrieve the current sensor value
      exec: /usr/bin/bash
      # (optional) arguments to pass to the executable
      args: [ '/home/celebrimbor/max-gpu-temp.sh' ]

curves:
  - id: gpu_curve
    # The type of the curve, one of: linear | function
    linear:
      # The sensor ID to use as a temperature input
      sensor: cmd_max_gpu
      # Sensor input value at which the curve is at minimum speed
      min: 30
      # Sensor input value at which the curve is at maximum speed
      max: 75
      
statistics:
  # Whether to enable the prometheus exporter or not
  enabled: true
  # The port to expose the exporter on
  port: 9000
  
runFanInitializationInParallel: false
```

`max-gpu-temp.sh`
```Shell
#!/bin/bash

echo $(( $(/usr/bin/nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader | sort -g | tail -n 1) * 1000 ))
```

**Comment by markusressel** [comment] 2022-09-30 16:25
Hmm I cannot see anything obviously wrong there.
What log output do you get when you run the daemon with ` --verbose`?

Should look something like this:
```
INFO: Using configuration file at: ./fan2go_m16.yaml
WARNING: Unused curve configuration: cpu_curve2
INFO: Starting statistics server...
INFO: Starting REST server...
INFO: Gathering sensor data for cpu_fan...
⇨ http server started on 127.0.0.1:9001
INFO: Loading fan curve data for fan 'cpu_fan'...
INFO: PWM settings of fan 'cpu_fan': Min 0, Start 1, Max 255
INFO: Starting controller loop for fan 'cpu_fan'

```

**Comment by mcgrizzz** [comment] 2022-10-02 03:08
This is what I get when running fan2go with the verbose flag. 

```bash
 INFO  Using configuration file at: /etc/fan2go/fan2go.yaml
 INFO  Starting statistics server...
 INFO  Gathering sensor data for BOTTOM_MIDDLE...
 INFO  Gathering sensor data for BOTTOM_LEFT...
 INFO  Gathering sensor data for FRONT_TOP...
 INFO  Gathering sensor data for CPU_MIDDLE...
 INFO  Gathering sensor data for CPU_FRONT...
 INFO  Gathering sensor data for BOTTOM_RIGHT...
 INFO  Gathering sensor data for FRONT_BOTTOM...
 INFO  Loading fan curve data for fan 'BOTTOM_LEFT'...
 INFO  Loading fan curve data for fan 'FRONT_BOTTOM'...
 INFO  Loading fan curve data for fan 'CPU_FRONT'...
 INFO  Loading fan curve data for fan 'CPU_MIDDLE'...
 INFO  Loading fan curve data for fan 'BOTTOM_MIDDLE'...
 INFO  Loading fan curve data for fan 'BOTTOM_RIGHT'...
 INFO  Loading fan curve data for fan 'FRONT_TOP'...
 INFO  PWM settings of fan 'BOTTOM_LEFT': Min 0, Start 0, Max 244
 INFO  Starting controller loop for fan 'BOTTOM_LEFT'
 INFO  PWM settings of fan 'BOTTOM_RIGHT': Min 0, Start 0, Max 238
 INFO  Starting controller loop for fan 'BOTTOM_RIGHT'
 INFO  PWM settings of fan 'CPU_MIDDLE': Min 0, Start 0, Max 253
 INFO  Starting controller loop for fan 'CPU_MIDDLE'
 INFO  PWM settings of fan 'FRONT_BOTTOM': Min 0, Start 0, Max 243
 INFO  Starting controller loop for fan 'FRONT_BOTTOM'
 INFO  PWM settings of fan 'BOTTOM_MIDDLE': Min 0, Start 0, Max 238
 INFO  Starting controller loop for fan 'BOTTOM_MIDDLE'
 INFO  PWM settings of fan 'FRONT_TOP': Min 0, Start 0, Max 250
 INFO  Starting controller loop for fan 'FRONT_TOP'
 INFO  PWM settings of fan 'CPU_FRONT': Min 0, Start 0, Max 250


```

**Comment by markusressel** [comment] 2022-10-02 17:21
I have restructured the webserver code quite a bit, please give it a new try with the latest version.

**Comment by mcgrizzz** [comment] 2022-10-02 18:38
I've tried out the newest version. It now serves the metrics endpoint correctly. It does, however, take around 30-40 seconds through the browser and around 10 seconds through curl to receive a response.

Is this expected?

**Comment by markusressel** [comment] 2022-10-02 19:57
Well thats some progress, but no, a 30 second delay is not expeted.
On my machine the response is delivered within a couple milliseconds.

**Comment by markusressel** [comment] 2022-10-22 21:33
I will go ahead and close this for now since I cannot reproduce the issue. If you find any new infos regarding this that need a fix in fan2go, feel free to post or create a new issue :nerd_face:

**Closed by markusressel** 2022-10-22 21:33 UTC
Labels: help wanted

**Comment by Maxr1998** [comment] 2026-05-10 17:48
I've been hit by this issue as well today, on the latest 0.13.0. I'm not entirely sure about the cause, but I purchased a new fan controller and redid my configuration because of that and wiped the existing database to start from scratch.

Now, scraping the metrics endpoint takes around 20 seconds, whereas directly on startup, it seems to complete much faster (as mentioned above). I noticed that because my Prometheus only managed to scrape data on startup, until raising the scrape timeout to 25 seconds. Still, 20 seconds to scrape some data, which should be available immediately, feels... off.

**Comment by Maxr1998** [comment] 2026-05-10 18:18
Ok, I think I found the cause. On my new Aquacomputer Octo, reading the current value in `pwm*` is rather slow, and it only gets worse when fan2go is running, potentially because it is trying to read back the current value *a lot*. I already tried disabling `pwmValueChangedByThirdParty` which didn't help much.
Reading rpm values is always quick, maybe because the kernel driver is caching those.

With fan2go running, trying to read pwm values takes ~3 seconds, even when setting the `adjustmentTickRate` to 2 seconds, and drops to the low 200ms if it is not running. So there definitely seems to be a congestion caused by fan2go.

**Comment by Maxr1998** [comment] 2026-05-10 19:47
That indeed seems to be it. The `aquacomputer_d5next` kernel driver enforces a minimum duration of 200 ms between PWM reads/writes ([source](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/blob/9ae7fd514d635f2d8bc5cdfefbbeecd4198641e9/aquacomputer_d5next.c#L866-L878)), which means that fan2go's operation mode of read/set/verify, as well as reading metrics from the device itself, rather than the cached average, causes this behavior.

The first issue is less a metrics issue and more a question of how to support devices with drivers like that so that long waits between operations don't stall the whole software.

The other question is whether the metrics endpoint should read fresh values itself, or instead simply return the last value that was read by the control loop, to keep the metrics endpoint responsive.

**Comment by markusressel** [comment] 2026-05-12 00:41
Hi @Maxr1998 thx for the investigation, that makes a lot of sense.

> With fan2go running, trying to read pwm values takes ~3 seconds, even when setting the adjustmentTickRate to 2 seconds, and drops to the low 200ms if it is not running. So there definitely seems to be a congestion caused by fan2go.

Yeah that might be the first thing to tackle here. Although I certainly think the driver should handle this better, that most certainly won't happen and it might be that fan2go does unnecessary reads during the controlloop that we can optimize out.

> The other question is whether the metrics endpoint should read fresh values itself, or instead simply return the last value that was read by the control loop, to keep the metrics endpoint responsive.

I have also had this thought when implementing the metrics endpoint initially, but at that time it seemed like massive overhead, because it would require some kind of internal data collection structure to retain values - at least if it was to be solved globally. Currently it is up to each fan/sensor type's implementation how to handle that, and that currently means "requesting it from the source". Besides the statistics endpoint it might also be useful to have a cached value ready for the controlloop, but a cache always comes at the cost of outdated information, so I am not entirely sure here.

In any case, if you would like to have a shot at it, feel free to checkout the repo.
As the original issue is solved and the statistics endpoint is not the problem directly, I will not repopen this issue. If you want to start a discussion please create new issue(s) for these topics.

**Comment by Maxr1998** [comment] 2026-05-13 19:05
> Yeah that might be the first thing to tackle here. Although I certainly think the driver should handle this better, that most certainly won't happen and it might be that fan2go does unnecessary reads during the controlloop that we can optimize out.

True, I'm unsure why the driver doesn't do more caching for example. I'll likely report the issue there too, but it might take a while before it's fixed, and optimizing the code here doesn't hurt either in the general case.

> I have also had this thought when implementing the metrics endpoint initially, but at that time it seemed like massive overhead, because it would require some kind of internal data collection structure to retain values - at least if it was to be solved globally. Currently it is up to each fan/sensor type's implementation how to handle that, and that currently means "requesting it from the source". Besides the statistics endpoint it might also be useful to have a cached value ready for the controlloop, but a cache always comes at the cost of outdated information, so I am not entirely sure here.

That's true, but at least for the PWM value I'm unsure how often that changes when only* we're the ones setting it.

*Or so I'd hope, unless an external application interferes. Even then, this should be limited to the `pwmValueChangedByThirdParty` check being enabled.

> In any case, if you would like to have a shot at it, feel free to checkout the repo. As the original issue is solved and the statistics endpoint is not the problem directly, I will not repopen this issue. If you want to start a discussion please create new issue(s) for these topics.

I can give it a go when I have some time. I thankfully have a little experience with Golang already, so that shouldn't be an issue.

And fair point on creating a new issue. I mostly wanted to get this started and wait for your initial feedback before doing so, but I'll definitely open one for my suggestions.
